export interface PortfolioProject {
  slug: string
  title: string
  category: string
  url: string
  location: string
  description: string
  about: string
  services: string[]
  seoMeta: {
    title: string
    description: string
  }
}

export const portfolioProjects: PortfolioProject[] = [
  {
    slug: "mazaya-dental-center",
    title: "Mazaya Dental Center",
    category: "Healthcare",
    url: "https://www.mazayadc.com/",
    location: "Kerala, India",
    description: "Premium dental clinic providing world-class oral care services.",
    about: "Mazaya Dental Center is a premium dental clinic offering world-class oral care services. We built them a fast, modern website that reflects the clinic's high standards, with online appointment booking and a clean design that builds patient trust from the first visit.",
    services: ["Business Website", "Brand Identity", "SEO"],
    seoMeta: {
      title: "Mazaya Dental Center | Portfolio | Digital Mitra",
      description: "How Digital Mitra built a modern, patient-friendly website for Mazaya Dental Center — a premium dental clinic in Kerala.",
    },
  },
  {
    slug: "lakshmi-ayurvedic",
    title: "Lakshmi Ayurvedic",
    category: "Healthcare",
    url: "https://www.lakshmiayurvedic.com/",
    location: "Kerala, India",
    description: "Traditional Ayurvedic healing and wellness center.",
    about: "Lakshmi Ayurvedic is a traditional Ayurvedic healing center with deep roots in Kerala's wellness heritage. We crafted a website that communicates authenticity and trust, showcasing their treatments and making it easy for patients to learn about and book their healing journey.",
    services: ["Business Website", "SEO", "Brand Identity"],
    seoMeta: {
      title: "Lakshmi Ayurvedic | Portfolio | Digital Mitra",
      description: "How Digital Mitra helped Lakshmi Ayurvedic establish a strong online presence for their traditional healing center in Kerala.",
    },
  },
  {
    slug: "rebalance-therapy",
    title: "Rebalance Therapy",
    category: "Wellness",
    url: "https://rebalancetherapy.co.in/",
    location: "India",
    description: "Mental well-being platform for holistic therapy.",
    about: "Rebalance Therapy is a mental well-being platform connecting clients with holistic therapists. We designed and built a calm, approachable website that helps destigmatize mental health and makes it simple for users to explore therapy options and get started.",
    services: ["Business Website", "Brand Identity", "SEO"],
    seoMeta: {
      title: "Rebalance Therapy | Portfolio | Digital Mitra",
      description: "How Digital Mitra built a calming and accessible web platform for Rebalance Therapy's holistic mental well-being services.",
    },
  },
  {
    slug: "map-the-world",
    title: "Map The World",
    category: "Travel",
    url: "https://www.maptheworld.in/",
    location: "Kochi, Kerala",
    description: "Kerala's premier travel & tourism experts.",
    about: "Map The World is one of Kerala's leading travel and tourism companies. We built them a visually rich website designed to inspire wanderlust, with destination pages, package listings, and a seamless inquiry flow to convert visitors into customers.",
    services: ["Business Website", "SEO", "Digital Marketing"],
    seoMeta: {
      title: "Map The World | Portfolio | Digital Mitra",
      description: "How Digital Mitra built a travel-inspiring website and digital marketing strategy for Map The World, Kerala's premier travel company.",
    },
  },
  {
    slug: "malayalam-holidays",
    title: "Malayalam Holidays",
    category: "Travel",
    url: "https://malayalamholidays.in/",
    location: "Kochi, Kerala",
    description: "Personalized travel agency based in Kochi.",
    about: "Malayalam Holidays is a Kochi-based travel agency specializing in personalized tour packages. We created a warm, welcoming website that highlights their curated travel experiences and makes it easy for customers to plan and book their dream holidays.",
    services: ["Business Website", "SEO", "Brand Identity"],
    seoMeta: {
      title: "Malayalam Holidays | Portfolio | Digital Mitra",
      description: "How Digital Mitra helped Malayalam Holidays grow their online travel bookings with a new website and SEO strategy.",
    },
  },
  {
    slug: "ragi-hospitality",
    title: "Ragi Hospitality",
    category: "Hospitality",
    url: "https://ragihospitalities.com/",
    location: "Kochi, Kerala",
    description: "Hotel marketing & management specialists in Kochi.",
    about: "Ragi Hospitality provides specialized hotel marketing and management services across Kerala. We built them a professional website that positions their expertise and helps hotel owners understand the value they bring, with clear service pages and a strong contact flow.",
    services: ["Business Website", "Digital Marketing", "SEO"],
    seoMeta: {
      title: "Ragi Hospitality | Portfolio | Digital Mitra",
      description: "How Digital Mitra built the digital presence for Ragi Hospitality, hotel marketing specialists in Kochi, Kerala.",
    },
  },
  {
    slug: "ideator-events",
    title: "Ideator Events",
    category: "Events",
    url: "https://www.ideator.events/",
    location: "Kerala, India",
    description: "Full-service event management and planning company.",
    about: "Ideator Events is a full-service event management company handling everything from corporate events to large-scale productions. We built a bold, energetic website that showcases their event portfolio and makes it easy for corporate clients to get in touch.",
    services: ["Business Website", "Brand Identity"],
    seoMeta: {
      title: "Ideator Events | Portfolio | Digital Mitra",
      description: "How Digital Mitra created a bold digital identity for Ideator Events, a full-service event management company in Kerala.",
    },
  },
  {
    slug: "guideline-edu",
    title: "Guideline Edu",
    category: "Education",
    url: "https://www.guidelineedu.com",
    location: "Kerala, India",
    description: "University admissions and educational consultancy.",
    about: "Guideline Edu is an educational consultancy helping students navigate university admissions in India and abroad. We built them a professional, trustworthy website with clear service pages, a student inquiry system, and SEO to attract students searching for admission guidance.",
    services: ["Business Website", "SEO", "Digital Marketing"],
    seoMeta: {
      title: "Guideline Edu | Portfolio | Digital Mitra",
      description: "How Digital Mitra built the website and SEO strategy for Guideline Edu, a leading educational consultancy in Kerala.",
    },
  },
  {
    slug: "episteme-academy",
    title: "Episteme Academy",
    category: "Education",
    url: "https://www.epistemeacademy.in/",
    location: "Mumbai, India",
    description: "Premium tuition academy based in Mumbai.",
    about: "Episteme Academy is a premium tuition academy in Mumbai serving students across multiple grades. We built them a modern educational website with course listings, faculty profiles, and an online enrollment flow to make it easy for parents to get their children enrolled.",
    services: ["Business Website", "Brand Identity", "SEO"],
    seoMeta: {
      title: "Episteme Academy | Portfolio | Digital Mitra",
      description: "How Digital Mitra helped Episteme Academy in Mumbai grow student enrollments with a new website and brand identity.",
    },
  },
  {
    slug: "earnest-financial",
    title: "Earnest Financial",
    category: "Finance",
    url: "https://www.earnestfinancial.com.au/",
    location: "Australia",
    description: "Business & personal loan specialists in Australia.",
    about: "Earnest Financial is an Australian financial services company specializing in business and personal loans. We built them a clean, compliance-friendly website that establishes trust with potential borrowers and clearly explains their loan products and application process.",
    services: ["Business Website", "Brand Identity"],
    seoMeta: {
      title: "Earnest Financial | Portfolio | Digital Mitra",
      description: "How Digital Mitra built a trust-driven website for Earnest Financial, a loan specialist company based in Australia.",
    },
  },
  {
    slug: "cluster-fascination",
    title: "Cluster Fascination",
    category: "eCommerce",
    url: "https://www.clusterfascination.com/",
    location: "India",
    description: "Fashion jewellery & accessories marketplace.",
    about: "Cluster Fascination is a fashion jewellery and accessories brand with a wide catalogue of trendy pieces. We built them a full-featured e-commerce website with product catalogues, a smooth checkout experience, and a brand identity that resonates with their fashion-forward audience.",
    services: ["Business Website", "Brand Identity", "Digital Marketing"],
    seoMeta: {
      title: "Cluster Fascination | Portfolio | Digital Mitra",
      description: "How Digital Mitra built the e-commerce platform and brand identity for Cluster Fascination, a fashion jewellery marketplace.",
    },
  },
  {
    slug: "nilaa-trends",
    title: "Nilaa Trends",
    category: "eCommerce",
    url: "https://www.nilaatrends.com",
    location: "India",
    description: "Contemporary clothing & fashion brand.",
    about: "Nilaa Trends is a contemporary clothing and fashion brand targeting modern Indian consumers. We designed and built their e-commerce store with a clean, editorial aesthetic, optimized product pages, and an intuitive shopping experience that drives conversions.",
    services: ["Business Website", "Brand Identity", "SEO"],
    seoMeta: {
      title: "Nilaa Trends | Portfolio | Digital Mitra",
      description: "How Digital Mitra built the e-commerce store and brand identity for Nilaa Trends, a contemporary clothing brand.",
    },
  },
  {
    slug: "map-my-property",
    title: "Map My Property",
    category: "Real Estate",
    url: "https://www.mapmyproperty.in/",
    location: "India",
    description: "Comprehensive real estate & property solutions.",
    about: "Map My Property is a comprehensive real estate platform offering property listings, consultancy, and investment solutions. We built them a feature-rich website with advanced property search, detailed listing pages, and an SEO strategy to attract buyers and sellers in a competitive market.",
    services: ["Business Website", "SEO", "Digital Marketing"],
    seoMeta: {
      title: "Map My Property | Portfolio | Digital Mitra",
      description: "How Digital Mitra built a property listing platform and SEO strategy for Map My Property, a leading real estate company.",
    },
  },
  {
    slug: "weald-west",
    title: "Weald West",
    category: "Export",
    url: "https://www.wealdwest.com/",
    location: "Wayanad, Kerala",
    description: "Natural products & agri exports from Wayanad.",
    about: "Weald West is a natural products and agricultural exports company based in Wayanad, Kerala. We built them a professional B2B website that tells their story of sustainable sourcing and makes it easy for international buyers to browse their catalogue and get in touch.",
    services: ["Business Website", "Brand Identity"],
    seoMeta: {
      title: "Weald West | Portfolio | Digital Mitra",
      description: "How Digital Mitra helped Weald West reach international buyers with a professional export company website.",
    },
  },
  {
    slug: "infinite-group",
    title: "Infinite Group",
    category: "Creative",
    url: "https://www.infinite-grp.com/",
    location: "UAE, Qatar & India",
    description: "Multi-industry group operating in UAE, Qatar & India.",
    about: "Infinite Group is a multi-industry conglomerate with operations across UAE, Qatar, and India. We built them a sophisticated corporate website that unifies their diverse business verticals under one strong brand, with professional imagery and clear navigation for each division.",
    services: ["Business Website", "Brand Identity"],
    seoMeta: {
      title: "Infinite Group | Portfolio | Digital Mitra",
      description: "How Digital Mitra built the corporate website for Infinite Group, a multi-industry conglomerate operating across UAE, Qatar, and India.",
    },
  },
  {
    slug: "creatudio",
    title: "Creatudio",
    category: "Creative",
    url: "https://www.thecreatudio.com/",
    location: "India",
    description: "Full-service creative agency for VFX & advertising.",
    about: "Creatudio is a full-service creative agency specializing in VFX production and advertising. We designed a visually stunning, portfolio-driven website that reflects their creative excellence and attracts high-profile clients looking for premium production work.",
    services: ["Business Website", "Brand Identity"],
    seoMeta: {
      title: "Creatudio | Portfolio | Digital Mitra",
      description: "How Digital Mitra built a visually stunning website for Creatudio, a full-service VFX and creative agency.",
    },
  },
  {
    slug: "muva-design",
    title: "Muva Design",
    category: "Creative",
    url: "https://www.muvadesign.in/",
    location: "India",
    description: "State-of-the-art architectural visualization studio.",
    about: "Muva Design is a cutting-edge architectural visualization studio producing photorealistic renders and animations. We built them a visually immersive portfolio website that showcases the depth of their work and positions them as the premium choice for architects and developers.",
    services: ["Business Website", "Brand Identity"],
    seoMeta: {
      title: "Muva Design | Portfolio | Digital Mitra",
      description: "How Digital Mitra built an immersive portfolio website for Muva Design, an architectural visualization studio.",
    },
  },
  {
    slug: "power-diesel-engineering",
    title: "Power Diesel Engineering",
    category: "Industrial",
    url: "https://www.pdee.net/",
    location: "India",
    description: "Industrial gear & heavy-duty engine parts.",
    about: "Power Diesel Engineering is a manufacturer and supplier of industrial gears and heavy-duty engine parts. We built them a professional B2B website with detailed product catalogues, technical specifications, and a clear inquiry system to connect them with industrial buyers.",
    services: ["Business Website", "Brand Identity"],
    seoMeta: {
      title: "Power Diesel Engineering | Portfolio | Digital Mitra",
      description: "How Digital Mitra built a B2B product website for Power Diesel Engineering, a manufacturer of industrial gears and engine parts.",
    },
  },
  {
    slug: "wetoo-technical-services",
    title: "Wetoo Technical Services",
    category: "Industrial",
    url: "https://www.wetootech.com/",
    location: "India",
    description: "Specialized lifting solutions and technical services.",
    about: "Wetoo Technical Services provides specialized lifting solutions and technical maintenance services for industrial clients. We built them a clean, professional website that communicates their technical expertise and makes it easy for project managers to request quotes.",
    services: ["Business Website", "Brand Identity"],
    seoMeta: {
      title: "Wetoo Technical Services | Portfolio | Digital Mitra",
      description: "How Digital Mitra built a professional website for Wetoo Technical Services, specialists in industrial lifting solutions.",
    },
  },
  {
    slug: "yara-technologies",
    title: "Yara Technologies",
    category: "Tech",
    url: "https://www.yaratechnologiesllc.com/",
    location: "Dubai, UAE",
    description: "Surveillance, CCTV & AV solutions in Dubai.",
    about: "Yara Technologies is a Dubai-based technology company specializing in surveillance, CCTV, and audio-visual solutions. We built them a professional corporate website that showcases their technical capabilities and product range, targeting businesses and government clients in the UAE.",
    services: ["Business Website", "Brand Identity"],
    seoMeta: {
      title: "Yara Technologies | Portfolio | Digital Mitra",
      description: "How Digital Mitra built the website for Yara Technologies, a CCTV and AV solutions company based in Dubai.",
    },
  },
  {
    slug: "personify",
    title: "Personify",
    category: "Tech",
    url: "https://www.personify.so/",
    location: "India",
    description: "Innovative SaaS platform for personal branding.",
    about: "Personify is an innovative SaaS platform that helps professionals build and manage their personal brand online. We partnered with the team on their web presence strategy, building a conversion-focused landing page and brand identity that communicates their unique value proposition to early adopters.",
    services: ["Business Website", "Brand Identity", "Business Automation"],
    seoMeta: {
      title: "Personify | Portfolio | Digital Mitra",
      description: "How Digital Mitra helped Personify, a personal branding SaaS platform, launch with a strong web presence and brand identity.",
    },
  },
  {
    slug: "cocoflo",
    title: "Cocoflo",
    category: "Construction",
    url: "https://www.cocoflo.in/",
    location: "Kerala, India",
    description: "Eco-friendly waterproofing and coconut wood products.",
    about: "Cocoflo is a Kerala-based company producing eco-friendly waterproofing solutions and sustainable coconut wood products. We built them a website that tells their sustainability story compellingly, with product pages and an inquiry system to reach architects, builders, and eco-conscious homeowners.",
    services: ["Business Website", "Brand Identity", "SEO"],
    seoMeta: {
      title: "Cocoflo | Portfolio | Digital Mitra",
      description: "How Digital Mitra built the website for Cocoflo, an eco-friendly waterproofing and coconut wood products company from Kerala.",
    },
  },
]
